logging:
  level: INFO
  loggers:
    com.finx: DEBUG
server:
  applicationConnectors:
    - type: http
      port: 14893
  adminConnectors:
    - type: http
      port: 14894

database:
  driverClass: org.postgresql.Driver
  url: ${POSTGRES_URL:-jdbc:postgresql://localhost:5432/sampleservicedb}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
