logging:
  level: INFO
  loggers:
    com.finx: DEBUG
server:
  applicationConnectors:
    - type: http
      port: 10885
  adminConnectors:
    - type: http
      port: 10886

database:
  driverClass: org.postgresql.Driver
  url: ${POSTGRES_URL:-jdbc:postgresql://localhost:5432/masterdataservicedb}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
